# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

target "CatenaxioIOS" do
pod 'JSONModel'
end

target "CatenaxioIOSTests" do

end

